language: node_js
before_install:
  - npm install -g eslint
  - npm install -g mocha
sudo: false # this opts into the container-base infrastructure that has no sudo commnand avaliable, but runs much faster
node_js:
  - "6"
  - stable